"""initial schema

Revision ID: 93eb07a2a38f
Revises: 
Create Date: 2026-08-28 13:36:52.230589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93eb07a2a38f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('customer_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('telephone', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('CHAR_LENGTH(TRIM(email)) > 0', name='chk_customer_email_not_blank'),
    sa.CheckConstraint('CHAR_LENGTH(TRIM(first_name)) > 0', name='chk_customer_first_name_not_blank'),
    sa.CheckConstraint('CHAR_LENGTH(TRIM(last_name)) > 0', name='chk_customer_last_name_not_blank'),
    sa.CheckConstraint('CHAR_LENGTH(TRIM(password_hash)) > 0', name='chk_customer_password_hash_not_blank'),
    sa.CheckConstraint('CHAR_LENGTH(TRIM(telephone)) > 0', name='chk_customer_telephone_not_blank'),
    sa.PrimaryKeyConstraint('customer_id'),
    sa.UniqueConstraint('email', name='uk_customer_email')
    )
    op.create_table('room_type',
    sa.Column('room_type_id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('room_name', sa.String(length=100), nullable=False),
    sa.Column('room_size', sa.String(length=100), nullable=False),
    sa.Column('max_guests', sa.SmallInteger(), nullable=False),
    sa.Column('current_nightly_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('CHAR_LENGTH(TRIM(room_name)) > 0', name='chk_room_type_room_name_not_blank'),
    sa.CheckConstraint('CHAR_LENGTH(TRIM(room_size)) > 0', name='chk_room_type_room_size_not_blank'),
    sa.CheckConstraint('current_nightly_rate > 0', name='chk_room_type_rate_positive'),
    sa.CheckConstraint('max_guests > 0', name='chk_room_type_max_guests_positive'),
    sa.PrimaryKeyConstraint('room_type_id'),
    sa.UniqueConstraint('room_name', name='uk_room_type_room_name')
    )
    op.create_table('reservation',
    sa.Column('reservation_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('room_type_id', sa.SmallInteger(), nullable=False),
    sa.Column('guest_count', sa.SmallInteger(), nullable=False),
    sa.Column('check_in_date', sa.Date(), nullable=False),
    sa.Column('check_out_date', sa.Date(), nullable=False),
    sa.Column('number_of_nights', sa.SmallInteger(), nullable=False),
    sa.Column('nightly_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('check_out_date > check_in_date', name='chk_reservation_date_order'),
    sa.CheckConstraint('guest_count > 0', name='chk_reservation_guest_count_positive'),
    sa.CheckConstraint('nightly_rate > 0', name='chk_reservation_rate_positive'),
    sa.CheckConstraint('number_of_nights = DATEDIFF(check_out_date, check_in_date)', name='chk_reservation_night_count'),
    sa.CheckConstraint('number_of_nights > 0', name='chk_reservation_nights_positive'),
    sa.CheckConstraint('total_cost = ROUND(nightly_rate * number_of_nights, 2)', name='chk_reservation_total'),
    sa.CheckConstraint('total_cost > 0', name='chk_reservation_total_positive'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_type.room_type_id'], ),
    sa.PrimaryKeyConstraint('reservation_id')
    )
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reservation_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservation_room_type_id'), ['room_type_id'], unique=False)
        batch_op.create_index('ix_reservation_stay_dates', ['check_in_date', 'check_out_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_index('ix_reservation_stay_dates')
        batch_op.drop_index(batch_op.f('ix_reservation_room_type_id'))
        batch_op.drop_index(batch_op.f('ix_reservation_customer_id'))

    op.drop_table('reservation')
    op.drop_table('room_type')
    op.drop_table('customer')
    # ### end Alembic commands ###
